# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53cb4468c4103e71b53290b2120101d8b94483a386fd542f4c37cceaa3653b9c08fc11ccf1a1b592497300d02443e6216b693fce27df57c99e1614f211fab8c2

test:
  secret_key_base: ff67d5359bde96a80b0d0c90020f0807778f68812e96999955494e3d8c761e019d4094081063c281919f902166753495dba03612061820e26e0f78e5ace3b2fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
